[project]
name = 'Tokenized-Community-Wind-Chime-Coordination-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.maintenance-scheduling-contract]
path = 'contracts/maintenance-scheduling-contract.clar'
clarity_version = 2
epoch = 2.5

[contracts.placement-optimization-contract]
path = 'contracts/placement-optimization-contract.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
